### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by MehranJanfeshan** [jaydata/JaySvcUtil#4]
Hi, 

 I am using JaySvcUtil.exe to generate model but every time that I run the command I will get this error :

Object reference not set to an instance of an object.
   at JaySvcUtil.Program.Main(String[] args)
I searched about it but I did not find anything about

Can you please help me on this ?

**Comment by robesz** [comment]
Hello Mehran,
could you please paste here the exact command - with parameters- that you run?

**Comment by MehranJanfeshan** [comment]
E:\MyProject\WebSite1\JaySvcUtil.exe --metadataUri http://localhost:49304/Service.svc

**Comment by MehranJanfeshan** [comment]
hello Robesz, 
I am running it on windows 10 , I do not know that this can cause any problem or not.

**Comment by robesz** [comment]
I guess you should add the /$metadata to the end of the URI. Does it fix the issue? Please check if your $metadata service is running and returns the XML

**Comment by MehranJanfeshan** [comment]
I added but still return the same error

**Comment by MehranJanfeshan** [comment]
Can you please send me a correct sample with my URL?

**Comment by robesz** [comment]
http://localhost:49304/Service.svc/$metadata should be the correct URL. Please check it in your browser if it is running. Does it work?

**Comment by MehranJanfeshan** [comment]
![error](https://cloud.githubusercontent.com/assets/13583839/10579775/b6ce34b4-76ac-11e5-9713-c24e17df2556.png)

**Comment by MehranJanfeshan** [comment]
now I am getting this error

**Comment by robesz** [comment]
right, your endpoint retunrs Bad request (status 400) according to the error message. JaySvcUtil cannot generate file if your endpont doesn't allow access to the metadata. 
This is usually cased by the authentication you configured. 
I suggest you to open your $metadata in incognito mode, I bet it will return the same error message.  If you are using basic auth, you can pass the userName and password parameters to the tool to authenticate.
If the $metadata cannot be accessed from your browser, jaysvcutil won't access it either.

**Comment by MehranJanfeshan** [comment]
OK, thank you, I will try and let you know.

**Comment by robesz** [comment]
in case you cannot authenticate to your service endpoint from jaysvcutil, you can open the endpoint in your browser, authenticate in your browser, save your metadata to a XML file next to your jaysvcutil.exe - filename:mymetadata.xml

You can run jaysvcutil.exe --metadataUri mymetadata.xml

**Comment by MehranJanfeshan** [comment]
I did the same thing but this round I got this error:

E:\MyProject\WebSite1\JaySvcUtil.exe  --metadataUri service.xml
Requesting: service.xml...
Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'C:\Users\mehran\service.xml'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at JaySvcUtil.Program.Main(String[] args)

file is not ready only

**Comment by MehranJanfeshan** [comment]
again I got the same error:
E:\MyProject\WebSite1\JaySvcUtil.exe  --metadataUri E:\MyProject\WebSite1\service.xml
Requesting: E:\MyProject\WebSite1\service.xml... done.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at JaySvcUtil.Program.Main(String[] args)

**Comment by robesz** [comment]
could you attach or paste the content of your XML file here?
